### ISSUE TITLE
Add a loader between login and register pages

### ISSUE THREAD

**Issue by soustab10** [FMC-Weekend/fmc24-client#102]
User needs to wait for about 30secs before redirecting to the dashboard/register page add a loader animation (any minimal animation accepted)

**Comment by soustab10** [comment]
@shubham21155102 update on this issue once the login to register issue is resolved. Till then this issue won't be assigned.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by soustab10** [comment]
This issue seems to be fixed. Closing this for now.
