### ISSUE TITLE
Add space between cards on Previous Guests

### ISSUE THREAD

**Issue by soustab10** [FMC-Weekend/fmc24-client#112]
- Remove Click to know more button
- Improve Mobilke View

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by subhh33** [comment]
HEY  @shubham21155102 ASSIGN ME FOR THIS ISSUE 
 THANK YOU 
YOUR ROOMMATE 
SUBHASH KUMAR
