### ISSUE TITLE
Worskhop Cards

### ISSUE THREAD

**Issue by soustab10** [FMC-Weekend/fmc24-client#126]
- Make cards for workshop 
- Make a vertical nav without any design(as design from Events page can be copied as is)

Hardcode worship names for now.
Also, some genre may not have any workshops, so design a basic "Workshops coming soon" card

**Comment by soustab10** [comment]
Copy the entire design and structure of the events page with changed workshop card. 
@Esod04 assigning it to you as you have designed events oage.

**Comment by soustab10** [comment]
@shruti2522 continue with this isuue.

**Comment by shubham21155102** [comment]
@Esod04 continue working on this
