### ISSUE TITLE
Teams Page

### ISSUE THREAD

**Issue by soustab10** [FMC-Weekend/fmc24-client#127]
- make teams page and cards 
- left part has all PORs and right part has basically a list fetched from a json.
-  Also it needs to have this function that on clicking say Publicity on left nav the right part will scroll and move to Publicity por holders. 

@mrunmayee7131 @Ashvita-6 are assigned.

**Comment by soustab10** [comment]
Team Data has been added you may start working. Also in place of image use any img for now.
@mrunmayee7131 @Ashvita-6

**Comment by AAKASHBANSAL96** [comment]
@soustab10 Please assign this to me.
