### ISSUE TITLE
User Dashboard fetching data from backend

### ISSUE THREAD

**Issue by shubham21155102** [FMC-Weekend/fmc24-client#82]

**Comment by AAKASHBANSAL96** [comment]
Please assign this to me

**Comment by shubham21155102** [comment]
Ok do it fast 
you will get backend url in the package.json

**Comment by AAKASHBANSAL96** [comment]
How is it possible to have backend URL in package.json @shubham21155102  ?

**Comment by shubham21155102** [comment]
Ooh wait wait i was thinking about another repo of this org.
I am providing you wait a minute

**Comment by shubham21155102** [comment]
Ooh wait wait i was thinking about another repo of this org.
I am providing you wait a minute 
REACT_APP_BACKEND_URI="https://fmcbackend.onrender.com"
@AAKASHBANSAL96

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102  Can you please give me more details about this URL, like is it GET request or POST and is there any authorization required?

**Comment by shubham21155102** [comment]
@AAKASHBANSAL96  you can refer to https://github.com/FMC-Weekend/fmcw-frontend
this repo for any such question

if you will still fin  issue mention me

**Comment by shubham21155102** [comment]
> @shubham21155102 Can you please give me more details about this URL, like is it GET request or POST and is there any authorization required?
> 
> as I visit on this url not showing any page.
> 
> ![Capture](https://user-images.githubusercontent.com/146818230/272932770-964c926a-28da-4256-acfc-86093bc248bf.PNG)

I am saying you to visit https://github.com/FMC-Weekend/fmcw-frontend/tree/main/src/components/pages/Dashboard. this page first

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102 I redirect to dashboard and it's showing me for authenticate. 
![dashboard](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/4e9bf48c-daf2-4f8c-adbb-b8230f8ae4e2)

**Comment by shubham21155102** [comment]
> @shubham21155102 I redirect to dashboard and it's showing me for authenticate. 
> ![dashboard](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/4e9bf48c-daf2-4f8c-adbb-b8230f8ae4e2)
> 

Give me your email id 
We will provide you .env file

**Comment by AAKASHBANSAL96** [comment]
Sure, aakash962002@gmail.com

**Comment by shubham21155102** [comment]
@AAKASHBANSAL96 
create a .env.local
File then add environment variables there

**Comment by shubham21155102** [comment]
@AAKASHBANSAL96 backend url is not coming in to action from .env.local

You can see you are getting undefined url

**Comment by AAKASHBANSAL96** [comment]
I have done changes and checked that not getting response from backend API
the token I have passed is token which saved in session but got message from response is user not found.

![response](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/fe8044fc-8f34-4c5f-8401-72eaaa907e05)
![reslt](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/4b5d3dd1-6f0c-4706-b2e6-833f178b4879)

**Comment by shubham21155102** [comment]
> I have done changes and checked that not getting response from backend API the token I have passed is token which saved in session but got message from response is user not found.
> 
> ![response](https://user-images.githubusercontent.com/146818230/272963443-fe8044fc-8f34-4c5f-8401-72eaaa907e05.PNG) ![reslt](https://user-images.githubusercontent.com/146818230/272963592-4b5d3dd1-6f0c-4706-b2e6-833f178b4879.PNG)

give me that email id by which you are signing in . I am going to do some changes for you in database

**Comment by AAKASHBANSAL96** [comment]
aakashdesigner96@gmail.com

**Comment by shubham21155102** [comment]
> Still same issue.

wait let me check the api

**Comment by shubham21155102** [comment]
const res = await fetch((url)+ 'api/user', {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                        email: email,
                    },
                });


for now we are passing email to backend so do that

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102 
The only data I'm receiving from API is:
`{
    "message": "success",
    "user": {
        "_id": "63cfe09ddac68f276197c459",
        "email": "aakashdesigner96@gmail.com",
        "name": "Aakash Designer",
        "role": -1,
        "__v": 0,
        "userCart": {
            "_id": "63cfe09ddac68f276197c45e",
            "forUser": "63cfe09ddac68f276197c45c",
            "cartItems": [],
            "__v": 0
        },
        "PaymentStatus": false
    }
} `
Missing value is: `College, Phone, Year of Study, Instagram Handle`

**Comment by shubham21155102** [comment]
hey @AAKASHBANSAL96 I have changed the backend pass the token as usual

**Comment by shubham21155102** [comment]
> @shubham21155102 The only data I'm receiving from API is: `{ "message": "success", "user": { "_id": "63cfe09ddac68f276197c459", "email": "aakashdesigner96@gmail.com", "name": "Aakash Designer", "role": -1, "__v": 0, "userCart": { "_id": "63cfe09ddac68f276197c45e", "forUser": "63cfe09ddac68f276197c45c", "cartItems": [], "__v": 0 }, "PaymentStatus": false } } ` Missing value is: `College, Phone, Year of Study, Instagram Handle`

go on /register route and register

**Comment by AAKASHBANSAL96** [comment]
> > @shubham21155102 The only data I'm receiving from API is: `{ "message": "success", "user": { "_id": "63cfe09ddac68f276197c459", "email": "aakashdesigner96@gmail.com", "name": "Aakash Designer", "role": -1, "__v": 0, "userCart": { "_id": "63cfe09ddac68f276197c45e", "forUser": "63cfe09ddac68f276197c45c", "cartItems": [], "__v": 0 }, "PaymentStatus": false } } ` Missing value is: `College, Phone, Year of Study, Instagram Handle`
> 
> go on /register route and register

Yes, this one is already done but the in `api/user` response not sending that values.

**Comment by shubham21155102** [comment]
okay @AAKASHBANSAL96  let me switch back to previous code

**Comment by AAKASHBANSAL96** [comment]
> okay @AAKASHBANSAL96 let me switch back to previous code

Yes, Please also check for the `api/user` response so I can get the missing values.

**Comment by AAKASHBANSAL96** [comment]
![success](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/04c1c727-9f61-4099-91f1-3f691b7184de)

**Comment by shubham21155102** [comment]
Yes nice

**Comment by AAKASHBANSAL96** [comment]
Now, Can I make PR?

**Comment by shubham21155102** [comment]
> Now, Can I make PR?

yes off course and also you can implement for add to cart etc ... that are available in https://github.com/FMC-Weekend/fmcw-frontend/tree/main/src/components/pages/Dashboard

**Comment by AAKASHBANSAL96** [comment]
For that can you please create new Issue or Feature requirement and assign to me so that I can on that from tomorrow 😊

**Comment by shubham21155102** [comment]
yes @AAKASHBANSAL96 off course do the pr for rest

**Comment by shubham21155102** [comment]
#86
