### ISSUE TITLE
fetch all the data like cart items in dashboard from backend

### ISSUE THREAD

**Issue by shubham21155102** [FMC-Weekend/fmc24-client#87]

**Comment by AAKASHBANSAL96** [comment]
Please assign it to me

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102 From where I can see that card items any screen route?

**Comment by shubham21155102** [comment]
https://github.com/FMC-Weekend/fmcw-frontend/tree/main/src%2Fcomponents%2Fpages%2FDashboard

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102 From where I can add card items to my account?

**Comment by shubham21155102** [comment]
> @shubham21155102 From where I can add card items to my account?
let me check the database for you

**Comment by shubham21155102** [comment]
Hey @AAKASHBANSAL96  just leave this because cart is empty and we are not currently adding any item to cart.
So if you wish to work more with us then you can work on adding a best payment gateway to usr website

**Comment by AAKASHBANSAL96** [comment]
Sure, I have experience of Integrating payment gateway like Stripe, Adyen, Paypal etc. 
Can we discuss about this on discord or an other platform ?

**Comment by shubham21155102** [comment]
@AAKASHBANSAL96 
https://join.slack.com/t/fmcweekend24/shared_invite/zt-24kkqkxnp-dPNpfT487XgRpOga9uHyNg
