### ISSUE TITLE
Add login to navbar

### ISSUE THREAD

**Issue by soustab10** [FMC-Weekend/fmc24-client#94]
- Add login to navbar
- On login, the login should change to dashboard
- Should connect to proper routes

**Comment by AAKASHBANSAL96** [comment]
Please assign this to me.

**Comment by shubham21155102** [comment]
@AAKASHBANSAL96  can you work on delay login 
because users are facing delay login

**Comment by AAKASHBANSAL96** [comment]
Yeah, sure we can add a loader to the screen If it's the issue from the backend response.

**Comment by shubham21155102** [comment]
> Yeah, sure we can add a loader to the screen If it's the issue from the backend response.

then go ahead

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102 I have used the existing loader component, and the loader is looking like this, is it okay? it should look in circular loading.

![image](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/d9d4dc82-0b84-4c95-8a8c-2d3198c91cc7)

**Comment by shubham21155102** [comment]
> @shubham21155102 I have used the existing loader component, and the loader is looking like this, is it okay? it should look in circular loading.
> 
> ![image](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/d9d4dc82-0b84-4c95-8a8c-2d3198c91cc7)
> 

Use BeatLoader 
By importing react-spinners package

**Comment by AAKASHBANSAL96** [comment]
I have updated the loading to this now.

![image](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/57c62744-06f0-4ccf-b1c4-adc1b7032130)

**Comment by AAKASHBANSAL96** [comment]
Added 

![image](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/7366a3cb-5bf8-493b-a00f-ce5754cf7feb)

**Comment by shubham21155102** [comment]
> Added
> 
> ![image](https://user-images.githubusercontent.com/146818230/273370993-7366a3cb-5bf8-493b-a00f-ce5754cf7feb.png)

nice 
leave the background as usual 
also keep the header as usual 
only login component would have a loader

**Comment by AAKASHBANSAL96** [comment]
![image](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/a0cd2b46-941e-44dc-aada-1058325b5893)

**Comment by AAKASHBANSAL96** [comment]
> > Added
> > ![image](https://user-images.githubusercontent.com/146818230/273370993-7366a3cb-5bf8-493b-a00f-ce5754cf7feb.png)
> 
> nice leave the background as usual also keep the header as usual only login component would have a loader

Do you mean the loader should be in this area?

![image](https://github.com/FMC-Weekend/fmc24-client/assets/146818230/4b437cd5-bd39-49c5-8913-0a8063092199)

**Comment by shubham21155102** [comment]
> > > Added
> > > ![image](https://user-images.githubusercontent.com/146818230/273370993-7366a3cb-5bf8-493b-a00f-ce5754cf7feb.png)
> > 
> > 
> > nice leave the background as usual also keep the header as usual only login component would have a loader
> 
> Do you mean the loader should be in this area?
> 
> ![image](https://user-images.githubusercontent.com/146818230/273371391-4b437cd5-bd39-49c5-8913-0a8063092199.png)

yes

**Comment by AAKASHBANSAL96** [comment]
> > > > Added
> > > > ![image](https://user-images.githubusercontent.com/146818230/273370993-7366a3cb-5bf8-493b-a00f-ce5754cf7feb.png)
> > > 
> > > 
> > > nice leave the background as usual also keep the header as usual only login component would have a loader
> > 
> > 
> > Do you mean the loader should be in this area?
> > ![image](https://user-images.githubusercontent.com/146818230/273371391-4b437cd5-bd39-49c5-8913-0a8063092199.png)
> 
> yes

What about when the user clicks login and after that user is redirected to the dashboard or register page?

**Comment by shubham21155102** [comment]
> > > > > Added
> > > > > ![image](https://user-images.githubusercontent.com/146818230/273370993-7366a3cb-5bf8-493b-a00f-ce5754cf7feb.png)
> > > > 
> > > > 
> > > > nice leave the background as usual also keep the header as usual only login component would have a loader
> > > 
> > > 
> > > Do you mean the loader should be in this area?
> > > ![image](https://user-images.githubusercontent.com/146818230/273371391-4b437cd5-bd39-49c5-8913-0a8063092199.png)
> > 
> > 
> > yes
> 
> What about when the user clicks login and after that user is redirected to the dashboard or register page?

logic has been written 
if new user then register page 
otherwise dashboard page


pull the recent changes

**Comment by AAKASHBANSAL96** [comment]
> > > > > > Added
> > > > > > ![image](https://user-images.githubusercontent.com/146818230/273370993-7366a3cb-5bf8-493b-a00f-ce5754cf7feb.png)
> > > > > 
> > > > > 
> > > > > nice leave the background as usual also keep the header as usual only login component would have a loader
> > > > 
> > > > 
> > > > Do you mean the loader should be in this area?
> > > > ![image](https://user-images.githubusercontent.com/146818230/273371391-4b437cd5-bd39-49c5-8913-0a8063092199.png)
> > > 
> > > 
> > > yes
> > 
> > 
> > What about when the user clicks login and after that user is redirected to the dashboard or register page?
> 
> logic has been written if new user then register page otherwise dashboard page
> 
> pull the recent changes

Yes I got that but I'm talking about the loader, don't we have to show the loader while the login process is working.

**Comment by AAKASHBANSAL96** [comment]
I mean to say that 
- User comes to the login page
- User clicks on login
- select account
- Loader start
- process for login
- loader stop
- redirect to it's required page.

**Comment by shubham21155102** [comment]
> I mean to say that
> 
> * User comes to the login page
> * User clicks on login
> * select account
> * Loader start (On login button area ?)(or full page loader ?)
> * process for login
> * loader stop
> * redirect to its required page.

yes

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102 I was working on it and it's done already I just need to push that code, I was not available in this 4-5 Days because of my office work.

**Comment by shubham21155102** [comment]
It's done @AAKASHBANSAL96

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102 No worry 😊

**Comment by AAKASHBANSAL96** [comment]
@shubham21155102 Please let me know if you have any issue that I can work on it.
