### ISSUE TITLE
Send email to mail from contact us form

### ISSUE THREAD

**Issue by soustab10** [FMC-Weekend/fmc24-client#95]
![image](https://github.com/FMC-Weekend/fmc24-client/assets/95632583/2998261d-4b29-4257-a0eb-05d8738e0c5b)

when user submits, a mail should be sent to specific mail and input area should be cleared

**Comment by AAKASHBANSAL96** [comment]
Please assign this to me.

**Comment by soustab10** [comment]
@shubham21155102 is already working on this
Thank you!
